name: Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Check
      run: cargo check
    - name: Run tests
      run: cargo test
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Check
      run: cargo check
    - name: Run tests
      run: cargo test
  build-mac:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Check
      run: cargo check
    - name: Run tests
      run: cargo test
